apiVersion: security.image/v1
kind: Tag
metadata:
  name: new-vulnerability
  namespace: dev
  labels:
    policy: infra
    env: prod
spec:
  image: ghcr.io/shravankamble/jwt-auth:v2
  vulnerabilities:
    critical: 7
    high: 10
    medium: 3
    low: 5